version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  labels:
  - Amélioration
  - Help Wanted
  - dependencies
  - À relire
  - À tester
  ignore:
  - dependency-name: codeception/codeception
    versions:
    - 4.1.14
    - 4.1.17
