language: php
php:
  - '7.1'
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
  irc:
    channel:
      - "irc.tuxfamily.org#Libertempo"
    on_success: never # default: change
    on_failure: always # default: always
#script: make test

jobs:
    includes:
        -
            # branch est apparemment la branch de base
            if: branch = master
            script: make test-functional
        -
            if: true
            script: make test-unit

after_script:
  - php Vendor/Bin/codacycoverage clover clover.xml
